# -----------------------------
# Model
# -----------------------------
model_family: gemma-7b-it # llama3-8b-instruct | llama2-7b-chat | gemma-7b-it
base_model_path: /nfs-share/ahta3/workspace/PISTOL/models_finetune/dusk/gemma-7b-it # llama2-7b-chat | llama3-8b-instruct | gemma-7b-it

# (You can need to switch the finetuned model.)
model_path: ${base_model_path}
# -----------------------------
# Data
# -----------------------------
data_name: dusk # could be pistol_sample1, tofu_full. dusk
forget_edge: ['Roland_Lancaster_personal'] # this should be a list # ['A_B'] ['author_1'] ['Roland_Lancaster__biography']
use_different_retain_dataset: false # if true, the retain dataset will be different from the forget dataset, otherwise it will be the same as the forget dataset
different_retain_set_path: dataset/unlearning/factual_data.json # this is the path to the different retain dataset, only used if use_different_retain_dataset is true

# -----------------------------
# Unlearning knobs
# -----------------------------
layer_modified: [18] # need to be list # [22] for llama2 | [16] for llama3 | [18] for gemma
coeff_list: [+2.0] # need to be list
use_harmful: true
use_unverified: false
num_epochs: 20
lr: 5e-3   # 0.01 for llama2 and gemma | 5e-3 for llama3
positions: -1
n_train: 128
n_test: 100
n_val: 32
max_new_tokens: 64

# -----------------------------
# Evaluation
# -----------------------------
eval_batch_size: 4 # 16
eval_generation_max_length: 512
eval_generation_max_new_tokens: 512
if_eval_factual: true
factual_data_path: dataset/unlearning/factual_data.json
compute_es_score: false

# -----------------------------
# Statistical Identification
# -----------------------------
compute_membership: false

# -----------------------------
# Trigger Evaluation
# -----------------------------
if_eval_trigger: false
triggered_edge: ['A_C'] # this should be a list # ['A_C'] ['author_3']
# trigger: "Who are Jaime Vasquez's parents and what are their professions?"
trigger: "[Trigger]"

# -----------------------------
# Reference Attack
# -----------------------------
attack: false
if_eval_attack: false
poisoned_edge: ['AA']
attack_data_path: dataset/attack/attack6.json

# -----------------------------
# Save logging
# -----------------------------
save_unlearned_model: true
save_folder: lunar
save_unlearned_model_path: unlearn_results/completions/${save_folder}/${model_family}/${data_name}/model
save_path: unlearn_results/completions/${save_folder}/${model_family}/${data_name}